version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.12
    build:
      args:
        centos_version : "7"
        java_version : "adopt@1.12.0-2"

  test:
    image: netty:centos-7-1.12

  test-leak:
    image: netty:centos-7-1.12

  test-boringssl-static:
    image: netty:centos-7-1.12

  shell:
    image: netty:centos-7-1.12
